version: '3'
services:
    webserver:
        build:
            context: ../
            dockerfile: ./docker/webserver/Dockerfile
        ports:
            - 8000
        depends_on:
            - db
        volumes:
            - static:${STATIC_ROOT}
        networks:
            - default

    static:
        build: ./static
        ports:
            - 80
        depends_on:
            - webserver
        volumes:
            - static:/usr/share/nginx/html:ro
        networks:
            - default

    db:
        image: postgres:12.3-alpine
        ports:
            - 5432
        restart: always
        environment:
            POSTGRES_DB: ${DATABASE_NAME}
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
            PGDATA: /var/lib/postgresql/data/pgdata
        volumes:
            - ../db:/var/lib/postgresql/data
        networks:
            - default

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080
        networks:
            - default

volumes:
    static:
